# Generated by Django 5.0.1 on 2024-03-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('backup', models.CharField(default='1', max_length=100)),
                ('project', models.TextField(max_length=10000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.webuser')),
            ],
        ),
    ]
